# To run netlify-cms locally:
#
# 1. Replace the `backend` config with the commented configuration below.
# 2. Remove the `src/` prefix from `file`, `folder` and `media_folder`
#    attributes to make them relative to the site URL, not relative to the repo
#    root (which is needed by the `github` backend which uses the GitHub API
#    endpoint to find files).
# 3. On the command line, run:
#        cd src && npx netlify-cms-proxy-server
#
# local_backend: true
# backend:
#   name: git-gateway
#
backend:
  name: github
  repo: dxw/playbook
  branch: main
  open_authoring: true
media_folder: src/assets/images
publish_mode: editorial_workflow
show_preview_links: true
collections:
  - name: home
    label: Home
    label_singular: Home page
    files:
      - name: home
        label: Home page
        file: src/index.md
        fields:
          - { label: Title, name: title, widget: string, required: true }
          - { label: Body, name: body, widget: markdown, required: true }

  - name: who-we-are
    label: Who we are
    label_singular: Who we are page
    folder: src/who-we-are
    create: true
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Permalink, name: permalink, widget: hidden, default: /:path/:basename/ }
      - { label: Body, name: body, widget: markdown, required: true }

  - name: work-we-do
    label: Work we do
    label_singular: Work we do page
    folder: src/work-we-do
    create: true
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Permalink, name: permalink, widget: hidden, default: /:path/:basename/ }
      - { label: Body, name: body, widget: markdown, required: true }
  - name: work-we-do__building-services
    label: Work we do > Building services
    label_singular: Building services page
    folder: src/work-we-do/building-services
    create: true
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Permalink, name: permalink, widget: hidden, default: /:path/:basename/ }
      - { label: Body, name: body, widget: markdown, required: true }

  - name: staff-handbook
    label: Staff handbook
    label_singular: Staff handbook page
    folder: src/staff-handbook
    create: true
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Permalink, name: permalink, widget: hidden, default: /:path/:basename/ }
      - { label: Body, name: body, widget: markdown, required: true }
  - name: staff-handbook__learning-and-development
    label: Staff handbook > Learning and development
    label_singular: Learning and development page
    folder: src/staff-handbook/learning-and-development
    create: true
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Permalink, name: permalink, widget: hidden, default: /:path/:basename/ }
      - { label: Body, name: body, widget: markdown, required: true }
  - name: staff-handbook__leave
    label: Staff handbook > Leave
    label_singular: Leave page
    folder: src/staff-handbook/leave
    create: true
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Permalink, name: permalink, widget: hidden, default: /:path/:basename/ }
      - { label: Body, name: body, widget: markdown, required: true }
  - name: staff-handbook__pay-pension-and-benefits
    label: Staff handbook > Pay, pension and benefits
    label_singular: Pay, pension and benefits page
    folder: src/staff-handbook/pay-pension-and-benefits
    create: true
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Permalink, name: permalink, widget: hidden, default: /:path/:basename/ }
      - { label: Body, name: body, widget: markdown, required: true }
  - name: staff-handbook__policies-and-procedures
    label: Staff handbook > Policies and procedures
    label_singular: Policies and procedures page
    folder: src/staff-handbook/policies-and-procedures
    create: true
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Permalink, name: permalink, widget: hidden, default: /:path/:basename/ }
      - { label: Body, name: body, widget: markdown, required: true }
  - name: staff-handbook__supporting-wellbeing
    label: Staff handbook > Supporting wellbeing
    label_singular: Supporting wellbeing page
    folder: src/staff-handbook/supporting-wellbeing
    create: true
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Permalink, name: permalink, widget: hidden, default: /:path/:basename/ }
      - { label: Body, name: body, widget: markdown, required: true }

  - name: commercial-ops
    label: Commercial Operations
    label_singular: Commercial Operations page
    folder: src/commercial-ops
    create: true
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Permalink, name: permalink, widget: hidden, default: /:path/:basename/ }
      - { label: Body, name: body, widget: markdown, required: true }

  - name: delivery-management
    label: Delivery Management
    label_singular: Delivery Management page
    folder: src/delivery-management
    create: true
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Permalink, name: permalink, widget: hidden, default: /:path/:basename/ }
      - { label: Body, name: body, widget: markdown, required: true }

  - name: design
    label: Design
    label_singular: Design page
    folder: src/design
    create: true
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Permalink, name: permalink, widget: hidden, default: /:path/:basename/ }
      - { label: Body, name: body, widget: markdown, required: true }

  - name: leadership
    label: Leadership
    label_singular: Leadership page
    folder: src/leadership
    create: true
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Permalink, name: permalink, widget: hidden, default: /:path/:basename/ }
      - { label: Body, name: body, widget: markdown, required: true }

  - name: product-management
    label: Product Management
    label_singular: Product Management page
    folder: src/product-management
    create: true
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Permalink, name: permalink, widget: hidden, default: /:path/:basename/ }
      - { label: Body, name: body, widget: markdown, required: true }

  - name: sales-and-marketing
    label: Sales and Marketing
    label_singular: Sales and Marketing page
    folder: src/sales-and-marketing
    create: true
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Permalink, name: permalink, widget: hidden, default: /:path/:basename/ }
      - { label: Body, name: body, widget: markdown, required: true }

  - name: tech
    label: Technology
    label_singular: Technology page
    folder: src/tech
    create: true
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Permalink, name: permalink, widget: hidden, default: /:path/:basename/ }
      - { label: Body, name: body, widget: markdown, required: true }

  - name: user-research
    label: User Research
    label_singular: User Research page
    folder: src/user-research
    create: true
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Permalink, name: permalink, widget: hidden, default: /:path/:basename/ }
      - { label: Body, name: body, widget: markdown, required: true }

  - name: govpress-unit
    label: GovPress Unit
    label_singular: GovPress Unit page
    folder: src/govpress-unit
    create: true
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Permalink, name: permalink, widget: hidden, default: /:path/:basename/ }
      - { label: Body, name: body, widget: markdown, required: true }

  - name: strategy-unit
    label: Strategy Unit
    label_singular: Strategy Unit page
    folder: src/strategy-unit
    create: true
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Permalink, name: permalink, widget: hidden, default: /:path/:basename/ }
      - { label: Body, name: body, widget: markdown, required: true }

  - name: redirects
    label: Redirects
    label_singular: Redirect manager
    files:
      - name: redirect-manager
        label: Redirect manager
        file: src/redirects.json
        fields:
          - label: Redirects
            name: redirects
            widget: "list"
            summary: '{{fields.from}} - {{fields.to}}'
            fields:
              - {label: Redirect from, name: from, widget: string, default: "/redirect-from"}
              - {label: Redirect to, name: to, widget: string, default: "/redirect-to"}
