name: Lint

on:
  - pull_request

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: errata-ai/vale-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
